### ISSUE TITLE
Improve overall code quality

### ISSUE THREAD

**Issue by scileo** [Tko1/ClojureRS#12]
The rust code in this repo is not very easy to read. This is caused by the lack of formatting. [`rustfmt`](https://github.com/rust-lang/rustfmt)  should be used in order to automatically format files before each commit, by using `cargo fmt`.

Additionally, warnings, whether if they come from `cargo check` or `cargo clippy` should be suppressed as much as possible. This allows us to keep a good code quality on the long run, and will improve overall productivity.

This issue proposes three changes, which *may* be solved in that order:
  - format code,
  - fix `cargo check` warnings,
  - fix `cargo clippy` warnings.

**Comment by Tko1** [comment]
Yes, the formatting is certainly a wart to remove.  For context, being human I feel I must be sure to add that this wasn't a case of ignorance;  before I knew there'd be this much interest and this was only a personal project, there were a few more liberties I was willing to take. One involved formatting, as I work on a tiny old thinkpad, and moreso I like to still have a million buffers open on my emacs,  so one thing you'll notice is a lot of highly vertical formatting like

```rust
        EnvironmentVal {
	    curr_ns: Namespace::new(Symbol::intern("user"),
				    RefCell::new(HashMap::new())),
	    namespaces: Namespaces(RefCell::new(HashMap::new()))
	}
```
in place of 
```rust	
        EnvironmentVal {
            curr_ns: Namespace::new(Symbol::intern("user"), RefCell::new(HashMap::new())),
            namespaces: Namespaces(RefCell::new(HashMap::new())),
        }
``` 
and other strange uses of newlines, especially as the second ends up linewrapping very early and looks terrible on my tiny screen.  Unfortunately for anyone else,  this sort of thing works very much for me, as I'm very used to using newlines this way and in other strange ways to easily be able to tell at a glance the structure of anything with any sort of nestedness, and sort of mentally jump around quickly.   

There are some similar formatting liberties, where I was experimenting with other ways yet of quickly grokking structure, but the motivations generally should be the same.   Regardless, yes,  this all certainly needs to be removed now, and I've incorporated skrapi's PR. 

As for the warnings, assuming we're looking at the same thing, there's about 45 (I should have more,  as I have several files not commited to the main repo) -- way too much. That being said, upon closer inspection, 33 of those are unused imports,  which is a result of a similar liberty;  these are all in areas that were rapidly changing (namely, everywhere, ahahah), where often an import goes out of use due to a refactoring, possibly comes back into use due to a refactoring, and goes out again.  I liked not having to keep adding and removing them, especially when changes sometimes this back-and-forth happens in a span of 10-15 minutes and it breaks my flow, and overall this is a particular warning I just preferred to batch-remove later, as things settled down (and this in fact has happened multiple times), especially as I don't believe it to be a significant hindrance, as long as it doesn't linger too long -- more imports at the top mean an extra second of scrolling, except often not even that (as my editor will skip past them either way).  Of course,  this is partially wrong; they are a hindrance in that they clutter the warning space, but regardless, there's that liberty.

A few warnings are unused functions,  and likewise I'd say these are ok as they are parts that I'm about to add in -- example being the `pub fn clojure_core_environment() -> Rc<Environment> {` , which is about to replace the hardcoded create-the-environment-from-scratch-in-main code. 

What's left then after all that are a few true warnings (some of those that are also just very recent changes in areas I know I'm about to look into changing anyways, such as the PartialEq definition on Value, although I think overall it'd be better to remove this sort of warning right away, as many don't take really any effort tbh).

Anyways, there's that unneeded context.   I don't forsee this being the only area to be refined, and I am sure some will not be as deliberate as these. I highly value posts like this, I want this project to be the best it can be, and implore anyone immediately write any other findings.

**Comment by Tko1** [comment]
Side note, another thing to be refactored off the top of my head is some highly nested matches in the reader (and some other places if I remember)

**Comment by scileo** [comment]
I wrote this issue after noticing that errors originating from macros are printed before warnings, so scrolling back to see them was really annoying.

I agree that having to clean warnings and other little things while working really breaks the flow. However, you don't have to do so. You may for example work in your own branch, introduce the features you need, and once happy with it, start fixing new warnings, and merge to `MASTER`. This allows other contributors to ensure the `MASTER` branch is clean.

About the size of your screen: I am also working on small screen (on ThinkPad too, btw), and keeping indentation level as small as possible is also an issue to me. However, I do see it as an advantage, since a high indentation level shows that some refactoring should be done. Code should be moved to new functions, and the `?` operator should be used more. These two little advices may seem difficult to apply, but I guarantee that your code will be way more readable for both you and your contributors.

The way you put whitespaces, as shown on the example you posted, is characteristic the LISP languages. To be honest, I think they suit well with S-expressions languages, where the goal is to put emphasis on data rather on the parenthesis, brackets and braces around them. However, Rust does not need that, since it has way less parenthesis, and so on.

To be honest, I think the problem comes from the fact that you're trying to write Rust "à la Lisp", which on the long run, will confuse future contributors, more used to read "regular" Rust code.

Finally, `rustfmt` may be configured, [as seen here](https://rust-lang.github.io/rustfmt/).

About warnings on unused functions: having some is totally fine as long as the concerned functions will be used in the future.
